/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Image_image.graphql
 * @generated SignedSource<<c87f54e41d7db89b93e839fa116fec69>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Image_image = {|
  +src: ?string;
  +alt: ?string;
  +originalHeight: ?number;
  +originalWidth: ?number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Image_image",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "src",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "alt",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "originalHeight",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "originalWidth",
      "storageKey": null
    }
  ],
  "type": "Image"
};

module.exports = fragment;
