/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PostLoopItem_post.graphql
 * @generated SignedSource<<f9adf8d7909125edd36bddc37828f673>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PostLoopItem_post = {|
  +id: string;
  +postId: ?string;
  +title: ?string;
  +date: ?number;
  +image: ?{| |};
  +category: ?string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "PostLoopItem_post",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "postId",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "title",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "date",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Image",
      "name": "image",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Image_image",
          "args": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "category",
      "storageKey": null
    }
  ],
  "type": "Post"
};

module.exports = fragment;
