#!/bin/sh

set -e

./scripts/support/build-wordpress

docker run --link viki-bell-website-mysql:viki-bell-website-mysql -p 2052:80 -v $(pwd)/data/uploads:/var/www/html/content/uploads -d x -e VIRTUAL_HOST=wordpress.charliejackson.com --env-file ./.env viki-bell-website-wordpress
