#!/bin/sh

./scripts/support/build-wordpress

docker run -v $(pwd)/cms/plugins:/var/www/html/content/plugins --link viki-bell-website-mysql:viki-bell-website-mysql -p 3005:80 -d --name viki-bell-website-wordpress --env-file ./.env viki-bell-website-wordpress
