#!/bin/sh

set -e

./scripts/support/build-wordpress

docker run --link viki-bell-website-mysql:viki-bell-website-mysql -p 3005:80 -v $(pwd)/data/uploads:/var/www/html/content/uploads -d --name viki-bell-website-wordpress --env-file ./.env viki-bell-website-wordpress
