#!/bin/sh
docker stop proxy
docker rm proxy

set -e

docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --name proxy jwilder/nginx-proxy
./scripts/support/run-mysql
./scripts/support/run-wordpress
./scripts/update-node
